language: php

addons:
  postgresql: "9.4"

services:
- mysql
- postgresql
- docker

cache:
  directories:
  - $HOME/.composer/cache
  - $HOME/.npm

php:
- 7.2
- 7.3

env:
  global:
  - PROFILE=chrome
  - MOODLE_START_BEHAT_SERVERS=NO
  matrix:
  - DB=pgsql MOODLE_REPO=https://github.com/moodleworkplace/multitenancy.git MOODLE_BRANCH=master EXCLUDETAGS=&&~@moodleworkplace
  - DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE
  - DB=mysql MOODLE_REPO=https://github.com/moodleworkplace/multitenancy.git MOODLE_BRANCH=master EXCLUDETAGS=&&~@moodleworkplace
  - DB=mysql MOODLE_BRANCH=MOODLE_38_STABLE

before_install:
- phpenv config-rm xdebug.ini
- nvm install 8.9
- nvm use 8.9
- cd ../..
- composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
- export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
- ls
- pwd

install:
- moodle-plugin-ci install -vvv
- docker run -d -p 127.0.0.1:4444:4444 --net=host -v /dev/shm:/dev/shm selenium/standalone-${PROFILE}:3
- php -S localhost:8000 -t $HOME/build/moodle > /dev/null 2>&1 &

script:
- moodle-plugin-ci phplint
- moodle-plugin-ci phpcpd
- moodle-plugin-ci phpmd
- moodle-plugin-ci codechecker
- moodle-plugin-ci validate
- moodle-plugin-ci savepoints
- moodle-plugin-ci mustache
- moodle-plugin-ci grunt
- moodle-plugin-ci phpdoc
- moodle-plugin-ci phpunit
- cd moodle
- php admin/tool/behat/cli/run.php --tags=@local_tenantexample$EXCLUDETAGS --profile=$PROFILE
