language: php

sudo: true

addons:
  firefox: "47.0.1"
  postgresql: "9.4"

services:
- mysql
- postgresql

cache:
  directories:
  - $HOME/.composer/cache
  - $HOME/.npm

php:
- 7.2
- 7.3

env:
  global:
  - MOODLE_BRANCH=master
  - MOODLE_REPO=git@github.com:moodleworkplace/multitenancy.git
  matrix:
  - DB=pgsql
  - DB=mysqli

before_install:
- phpenv config-rm xdebug.ini
- nvm install 8.9
- nvm use 8.9
- cd ../..
- composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
- export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
- moodle-plugin-ci install

script:
- moodle-plugin-ci phplint
- moodle-plugin-ci phpcpd
- moodle-plugin-ci phpmd
- moodle-plugin-ci codechecker
- moodle-plugin-ci validate
- moodle-plugin-ci savepoints
- moodle-plugin-ci mustache
- moodle-plugin-ci grunt
- moodle-plugin-ci phpdoc
- moodle-plugin-ci phpunit
- moodle-plugin-ci behat
